### ISSUE TITLE
Problem with install logging

### ISSUE THREAD

**Issue by Axel0008** [Axel0008/python_all#1]
windows 10
python python 3.7

Hi here!
I heve a problem with install module logging.
Error:
```
C:\Users\Admin>pip install logging
Collecting logging
  Using cached https://files.pythonhosted.org/packages/93/4b/979db9e44be09f71e85c9c8cfc42f258adfb7d93ce01deed2788b2948919/logging-0.4.9.6.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info\logging.egg-info
    writing pip-egg-info\logging.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\logging.egg-info\dependency_links.txt
    writing top-level names to pip-egg-info\logging.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\logging.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMIN~1\AppData\Local\Temp\pip-install-g99eayy5\logging\setup.py", line 13, in <module>
        packages = ["logging"],
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
        self.find_sources()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
        mm.run()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
        self.add_defaults()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\distutils\command\sdist.py", line 226, in add_defaults
        self._add_defaults_python()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
        return self.resolve()
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\build_py.py", line 15, in <module>
        from setuptools.lib2to3_ex import Mixin2to3
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\lib2to3_ex.py", line 12, in <module>
        from lib2to3.refactor import RefactoringTool, get_fixers_from_package
      File "c:\users\Admin\appdata\local\programs\python\python37-32\lib\lib2to3\refactor.py", line 18, in <module>
        import logging
      File "C:\Users\ADMIN~1\AppData\Local\Temp\pip-install-g99eayy5\logging\logging\__init__.py", line 618
        raise NotImplementedError, 'emit must be implemented '\
                                 ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMIN~1\AppData\Local\Temp\pip-install-g99eayy5\logging\
```
I do `pip install logging`
pip version 19.1.1
Please, help me! I can not find a solution.

**Comment by FangSen9000** [comment]
How did you deal with it？
